(ns brick.brick-test
  "Sample assembly for brick and ground."
  (:require [expectations :refer :all]
            [isis.geom.model
             [joint :refer [joint-primitive-map]]
             [graph :refer [make->link make->marker
                            port->expand
                            port-pair->make-constraint
                            graph->init-invariants
                            graph->expand-joint-pair ]]
             [invariant :refer [init-marker-invariant-s
                                init-link-invariant-s
                                init-link-invariant
                                marker->add-invariant!
                                make->invariant]]]
            [isis.geom.action-dispatch
             :refer [precondition?->transform!]]
            [isis.geom.action
             [coincident-slice]
             [helical-slice]
             [in-line-slice]
             [in-plane-slice]
             [offset-x-slice]
             [offset-z-slice]
             [parallel-z-slice]]))



(def brick-graph
  "From section 3.4 : Example 1: the brick
  This object is composed of the prime data for an assembly.
  The derived data should not be stored in this object directly,
  but be stored in other objects with simliar keys."
  (ref
   '{ :links
      { brick {
               :markers {b1 {:e1 -100.0 :e2 50.0 :e3 10.0}
                         b2 {:e1 -99.0 :e2 50.0 :e3 10.0}
                         b3 {:e1 -100.0 :e2 51.0 :e3 10.0} }
               :ports {j1 {:type :spherical :marker b1}
                       j2 {:type :spherical :marker b2}
                       j3 {:type :spherical :marker b3}} }
        ground {
                :markers {g1 {}
                          g2 {:e1 1.0 :e2 0.0 :e3 0.0}
                          g3 {:e1 0.0 :e2 1.0 :e3 0.0} }
                :ports {j1 {:type :spherical :marker g1}
                        j2 {:type :spherical :marker g2}
                        j3 {:type :spherical :marker g3}} } }
      :base ground
      :joints
      #{#{[ground j1] [brick j1]}
        #{[ground j2] [brick j2]}
        #{[ground j3] [brick j3]}} }))

(def brick-graph-goal
  "This shows the ultimate goal for the action-analysis.
  Notice that the ground has no properties, this idicates the
  use of the default values, it also indicates the 'base' object.
  In this example there is no rotation so the {:e12 :e23 :e31} values
  could be anything."
  '{:link-motors
    {ground {}
     brick {:e1 100.0 :e2 -50.0 :e3 -10.0}}})


(declare graph->expand-joints graph->action-analysis)

(defn make-graph-watcher
  "This function is suitable to use as a watch function.
  When a graph changes it will compute the placement of
  each link in its assembly.  The augmented graph will
  be produced by this function."
  []
  (defn graph->assemble
    [key reference old-state new-state]
    (graph->expand-joints new-state))

  (add-watch brick-graph :assembly-key graph->assemble) )


(expect '[[ground g1 :coincident {}]]
   (port->expand @brick-graph '[ground j1]))

(expect '{:type :coincident,
     :m1 [[ground g2] {:e2 0.0, :e3 0.0, :e1 1.0}],
     :m2 [[brick b2] {:e2 0.0, :e3 0.0, :e1 101.0}]}
   (port-pair->make-constraint
    @brick-graph
    '[[ground g2 :coincident {:e1 1.0, :e2 0.0, :e3 0.0}]
      [brick b2 :coincident {:e1 101.0, :e2 0.0, :e3 0.0}]] ))



(let [ ikb (graph->init-invariants @brick-graph)
       m (:m ikb), m-p (:p m), m-z (:z m), m-x (:x m)
       l (:l ikb), l-ground ('ground l) ]
  (do
   (= '#{[ground g1] [ground g2] [ground g3]} @m-p)
   (= '#{[ground g1] [ground g2] [ground g3]} @m-z)
   (= '#{[ground g1] [ground g2] [ground g3]} @m-x)
   (= '{:p {:e1 0.0, :e2 0.0, :e3 0.0, :e12 0.0, :e23 0.0, :e31 1.0, :t 0.0},
         :tdof {:# 3}, :rdof {:# 3}} l-ground)))

(expect '[{:type :coincident,
      :m1 [[ground g1] {}],
      :m2 [[brick b1] {:e1 -100.0, :e3 10.0, :e2 50.0}]}]
   (graph->expand-joint-pair @brick-graph '#{[ground j1] [brick j1]}))


(defn graph->expand-joints
  "Using a graph's joint definitions,
  generate a list of constraints for the joint primitives.
  Each constraint primitive is generated by merging
  corresponding ports."
  [graph]
  (mapcat identity
          (for [joint-pair (:joints graph)]
            (graph->expand-joint-pair graph joint-pair))))

(expect '({:type :coincident,
      :m1 [[ground g2] {:e1 1.0, :e3 0.0, :e2 0.0}],
      :m2 [[brick b2] {:e1 -99.0, :e3 10.0, :e2 50.0}]}
            {:type :coincident,
             :m1 [[ground g3] {:e1 0.0, :e3 0.0, :e2 1.0}],
             :m2 [[brick b3] {:e1 -100.0, :e3 10.0, :e2 51.0}]}
            {:type :coincident,
             :m1 [[ground g1] {}],
             :m2 [[brick b1] {:e1 -100.0, :e3 10.0, :e2 50.0}]})
   (graph->expand-joints @brick-graph))



brick-graph


(let [x '{:type :coincident,
          :m1 [[ground g1] {}],
          :m2 [[brick b1] {:e1 -100.0, :e3 10.0, :e2 50.0}]}
      ikb (graph->init-invariants @brick-graph)]
  (precondition?->transform! x ikb)
  (= [] ikb))

(defn action-analysis
  "Algorithm for using the plan fragment table to perform action alalysis.
  We update a link map and a marker map with invariants.
  The link map of invariants indicates just how well placed the link is.
  The marker map does a similar thing.
  - We will repeatedly evaluate all constraints, making marker properties
  invariant and producing link motors, until no more constraints can be satisfied.
  The link motors are then returned.
  constraints : the list of constraints needing to be satisfied.
  invariants : invariant properties of markers and links.

  ys : constraints which have been tried and failed.
  progress? : is the current round making progress?"
  [constraints invariants]
  (loop [ [x & xs] constraints,
          ys [], progress? true]
    (if-not x
      (if (empty? ys)
        ;; all the constraints have been satisfied
        invariants
        (if progress?
          ;; still making progress, try again.
          (recur ys [] true)
          ;; no progress is possible.
          invariants))
      ;; working through the constraint list.
      (if (precondition?->transform! x invariants)
        (recur xs ys true)
        (recur xs ys progress?) ))))


#_(let [graph @brick-graph
      constraints (graph->expand-joints graph)
      invariants (graph->init-invariants graph)
      result (action-analysis constraints invariants)]
  (let [marker (:m result)
        links (:g result)]
    (expect '#{[ground g1] [ground g2] [ground g3]} @(:p marker))
    (expect #{} @(:z marker))
    (expect #{} @(:x marker))
    (expect '{ground {:e1 1.0 :e2 2.0 :e3 3.0 :e12 0.0 :e23 0.0 :e31 1.0 :t 0.0}
              brick {:e1 1.0 :e2 2.0 :e3 3.0 :e12 0.0 :e23 0.0 :e31 1.0 :t 0.0}}
            @(:p links))))

